### ISSUE TITLE
Does not work, nor load using Obsidian with a Lenovo IdeaPad Duet (ChromeOS-ARM)

### ISSUE THREAD

**Issue by TRENEEDANAME** [arnau/obsidian-metatable#21] opened 2021-11-25 07:56 UTC
It does not load when the plugin is active, reinstalled and does not fix the issue, the YAML doesn't load with the plugin enable.
![Screenshot 2021-11-25 08 55 35](https://user-images.githubusercontent.com/79509045/143401586-8d14e201-857d-4521-b4b8-b6e67d5d515c.png)
![Screenshot 2021-11-25 08 55 26](https://user-images.githubusercontent.com/79509045/143401591-721f8984-8097-4ac8-a926-aa3433282c90.png)
![Screenshot 2021-11-25 08 54 53](https://user-images.githubusercontent.com/79509045/143401594-61b8d7de-bc09-4e79-9acc-7d7410241be0.png)

**Comment by arnau** [comment] 2021-11-26 11:51
I'm afraid I can't replicate the issue you are having. What other plugins do you have installed? Does it change behaviour when you disable them?

**Comment by TRENEEDANAME** [comment] 2021-11-26 16:41
I have tried on a new vault, no plugin, it's the same issue

**Comment by arnau** [comment] 2021-11-27 09:25
Thanks @TRENEEDANAME. I'll keep this open in case someone else can help replicate and narrow down.

**Comment by arnau** [comment] 2022-08-16 16:47
Closing as I still can't reproduce and no one has stepped forward with a fix.

**Closed by arnau** 2022-08-16 16:47 UTC
Labels: help wanted
