### ISSUE TITLE
metatable not working

### ISSUE THREAD

**Issue by s1avash26** [arnau/obsidian-metatable#46] opened 2023-01-28 15:00 UTC
Hello,
Thanks for developing such a great plugin, after just updating obsidian plugins metatable is not shown in preview mode:
for example I have this:
![metatable1](https://user-images.githubusercontent.com/65964655/215282146-a0283dd3-b53f-4cde-8ff1-590e24dfd5b2.jpg)

it becomes:
![metatable2](https://user-images.githubusercontent.com/65964655/215282176-6528d1ed-b5ca-4bf4-bde2-36112cd0aed4.jpg)

**Comment by arnau** [comment] 2023-01-29 10:52
Hey @s1avash26 , thanks for reporting. I need to look into your case properly but in the meanwhile could you tell me:

- version of Obsidian
- version of Metatable
- theme (whether it's the default or not)
- custom css (y/n)

Finally, if you have other plugins installed, during the metatable upgrade did they also upgrade? the problem is likely to be with metatable but I've seen some conflicts between plugins and better to check :)

**Comment by s1avash26** [comment] 2023-01-29 17:43
thank you for the response, I just struggled a few hours after that I found that I had updated "RTL" so I disabled it and then everything started working fine, I don't know why but maybe a collision.
I have updated everything to last version.

**Comment by arnau** [comment] 2023-01-30 07:56
Thanks for the update. I've never used RTL but a quick test doesn't show any issue. Let me know if you find any other clue so we can narrow down what could be the issue.

**Comment by arnau** [comment] 2023-07-09 11:44
Closing as I haven't been able to reproduce. Please let me know if it happens again so we can try to reduce the problem to a minimal tests case.

**Closed by arnau** 2023-07-09 11:44 UTC
Labels: unverified
