### ISSUE TITLE
Use markdown link form.

### ISSUE THREAD

**Issue by Peingxious** [arnau/obsidian-metatable#22] opened 2021-12-17 07:19 UTC
Can the link form of the original markdown syntax be quoted in double quotes to implement URI links without showing the link length.

Just like this
 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
"[🦅] (eagle://item/KXA1DFAZOATRW)"

Show only 🦅 to jump other APP.

**Comment by arnau** [comment] 2021-12-17 14:34
duplicate of #13

**Comment by Peingxious** [comment] 2021-12-23 02:24
> [#13 的](https://github.com/arnau/obsidian-metatable/issues/13)副本[](https://github.com/arnau/obsidian-metatable/issues/13)
Not the same, I want to customize the URI header, customize only a few URI headers. The link in Yaml is too long, I hope it can be reduced to think like dataview. Can use markdown links.
![](https://hbimg.huabanimg.com/a9c8deb4559415ca37c68d7860602e452fb523171f95-ifOMog)

**Comment by arnau** [comment] 2021-12-23 08:02
mmm, I'm not sure I understand. The example you share in the screenshot is a plain URL but the initial message says:

```
"[🦅] (eagle://item/KXA1DFAZOATRW)"
```

The first case has not enough information to display a short text unless I do an external request to fetch the page title or something like that. Which it is out of scope for this plugin (I don't want to make any external calls for security reasons).

The second is a markdown link which is the same case as per #13 which I _think_ should be doable when I manage to get some spare time.

Let me know if the above is what you meant and if not, could you help me understand? Thanks

**Comment by arnau** [comment] 2022-08-16 16:47
Closing as I can't follow the request.

**Closed by arnau** 2022-08-16 16:47 UTC
Labels: duplicate
