### ISSUE TITLE
Tags with emojis do not appear with Metatable (in Preview mode)

### ISSUE THREAD

**Issue by estheon** [arnau/obsidian-metatable#39] opened 2022-10-20 00:44 UTC
I use tags in the form of **emojis** to organize my Obsidian notes. Metatable used to display my emoji tags but for some reason the emojis no longer appear.

Here is the text in edit mode.
![image](https://user-images.githubusercontent.com/59342862/196830225-87a2a59f-42a8-4567-ae37-948d26cfdbdf.png)

Here is the text in preview mode.
![image](https://user-images.githubusercontent.com/59342862/196830369-bdbafacf-03cf-4bd7-8fda-60898e18b71b.png)

I did notice that when separating two emoji tags with a comma, this error appears:
![image](https://user-images.githubusercontent.com/59342862/196830432-c4c1a6a0-2c81-4050-9f0c-0e8954bd7d7d.png)

This error does not appear when the emoji tags are separated with a space bar.

When Metatable is turned off, the emoji tags become visible again in preview mode. Here is a picture of a note with two emoji tags:
![image](https://user-images.githubusercontent.com/59342862/196830603-9e62ea6d-57e3-4839-b585-2f51962a904d.png)

Would it be possible to restore Metatable's ability to show emoji tags? I would hate to re-tag every single note of mine with non-emoji tags.

**Comment by arnau** [comment] 2022-10-22 08:02
Hi @estheon, thanks for reporting. I'm afraid I can't reproduce the behaviour you are showing in these screenshots. Could you share the actual markdown file as well as the metatable version please?

**Comment by estheon** [comment] 2022-10-24 02:31
[Metatable Emoji Tag Debugging.md](https://github.com/arnau/obsidian-metatable/files/9848358/Metatable.Emoji.Tag.Debugging.md)

Here is the file from the screenshot above, it has two tags like in the last screenshot. My current Metatable version is 0.14.3, the latest version.

**Comment by arnau** [comment] 2022-10-25 07:18
The markdown file you shared works fine for me 😢 I'll think about what could make your instance not work, no immediate ideas right now though.

**Comment by arnau** [comment] 2022-10-25 07:20
If it doesn't work when you use the Preview I would expect it doesn't work either when you open the sidebar, is this correct?

**Comment by estheon** [comment] 2022-11-07 14:37
I just wanted to provide an update here: so it turns out that one of my other Obsidian vaults does show the emoji tags. I am going to compare the `.obsidian` folders of my two vaults and see what's preventing the emoji tags from showing in my original vault, and I will provide my updates soon. 

Thank you for your responsiveness, arnau!

**Comment by arnau** [comment] 2023-07-09 11:45
Closing as it doesn't seem to be an issue.

**Closed by arnau** 2023-07-09 11:45 UTC
Labels: unverified
